config/routes.rb
Bsboll::Application.routes.draw do
  devise_for :players

  root :to => 'startpage#index'
  
  resources :clubs, :except => :show
  resources :courses, :except => :show
  resources :matches do
    member do
      put :prev_hole, :next_hole, :goto_hole
      get :results
      post :score
    end
  end
end

app/models/club.rb
class Club < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  has_many :courses, :dependent => :destroy
  
  def to_s
    name
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => { :scope => :club_id }
  validates :club, :presence => true
  
  belongs_to :club
  has_many :holes, :dependent => :destroy, :order => :nr
  has_many :matches, :dependent => :destroy
  
  accepts_nested_attributes_for :holes
  
  def to_s
    name
  end
end

app/models/hole.rb
class Hole < ActiveRecord::Base
  belongs_to :course
  
  def to_s
    nr.to_s
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :course
  belongs_to :hole
  belongs_to :player
  has_many :teams, :dependent => :destroy
  has_many :scores, :dependent => :destroy

  validates :course, :presence => true

  accepts_nested_attributes_for :teams
  accepts_nested_attributes_for :scores

  def set_initial_hole
    self.hole = course.holes.find_by_nr(1)
  end
  before_create :set_initial_hole

  def prev_hole!
    goto_hole!(hole.nr - 1)
  end

  def next_hole!
    goto_hole!(hole.nr + 1)
  end

  def goto_hole!(nr)
    if (1..18).include?(nr)
      self.hole = course.holes.find_by_nr(nr)
    else
      self.hole = nil
    end
    save!
  end

  def score_for(player, hole = nil)
    Score.find_by_match_id_and_hole_id_and_player_id(self.id, hole || self.hole.id, player.id) || self.scores.build
  end

  def finished?
    hole.nil?
  end

  def team_1
    teams.first
  end

  def team_2
    teams.last
  end

  def has_score?(hole)
    Score.find_all_by_match_id_and_hole_id(self.id, hole).size == 4
  end

  def score
    player_1 = team_1.captain
    player_2 = team_1.player
    player_3 = team_2.captain
    player_4 = team_2.player

    shots_player_1 = team_1.shots_captain
    shots_player_2 = team_1.shots_player
    shots_player_3 = team_2.shots_captain
    shots_player_4 = team_2.shots_player

    team_1_score = 0
    team_2_score = 0

    course.holes.each do |hole|
      break unless has_score?(hole)

      hcp = hole.hcp
      par = hole.par

      team_1_score_hole = 0
      team_2_score_hole = 0

      shots_extra_on_hole_player_1 = (shots_player_1 / 18) + ((shots_player_1 % 18) >= hcp ? 1 : 0)
      shots_extra_on_hole_player_2 = (shots_player_2 / 18) + ((shots_player_2 % 18) >= hcp ? 1 : 0)
      shots_extra_on_hole_player_3 = (shots_player_3 / 18) + ((shots_player_3 % 18) >= hcp ? 1 : 0)
      shots_extra_on_hole_player_4 = (shots_player_4 / 18) + ((shots_player_4 % 18) >= hcp ? 1 : 0)

      score_on_hole_player_1 = score_for(player_1, hole).score
      score_on_hole_player_2 = score_for(player_2, hole).score
      score_on_hole_player_3 = score_for(player_3, hole).score
      score_on_hole_player_4 = score_for(player_4, hole).score

      point_on_hole_player_1 = [(par + shots_extra_on_hole_player_1) - score_on_hole_player_1 + 2, 0].max
      point_on_hole_player_2 = [(par + shots_extra_on_hole_player_2) - score_on_hole_player_2 + 2, 0].max
      point_on_hole_player_3 = [(par + shots_extra_on_hole_player_3) - score_on_hole_player_3 + 2, 0].max
      point_on_hole_player_4 = [(par + shots_extra_on_hole_player_4) - score_on_hole_player_4 + 2, 0].max

      team_1_worst_ball, team_1_best_ball = [point_on_hole_player_1, point_on_hole_player_2].sort
      team_2_worst_ball, team_2_best_ball = [point_on_hole_player_3, point_on_hole_player_4].sort

      if team_1_best_ball > team_2_best_ball
        team_1_score_hole += 2
      elsif team_1_best_ball < team_2_best_ball
        team_2_score_hole += 2
      end

      if team_1_worst_ball > team_2_worst_ball
        team_1_score_hole += 1
      elsif team_1_worst_ball < team_2_worst_ball
        team_2_score_hole += 1
      end

      if points_for_birdie > 0
        if par == score_on_hole_player_1 + 1 || par == score_on_hole_player_2 + 1
          team_1_score_hole += points_for_birdie
        end

        if par == score_on_hole_player_3 + 1 || par == score_on_hole_player_4 + 1
          team_2_score_hole += points_for_birdie
        end
      end

      team_1_score += team_1_score_hole
      team_2_score += team_2_score_hole
    end

    team_min_score = [team_1_score, team_2_score].min

    [team_1_score - team_min_score, team_2_score - team_min_score]
  end

  def players
    [team_1.captain, team_1.player, team_2.captain, team_2.player]
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :matches, :dependent => :destroy
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  
  validates :first_name, :last_name, :presence => true
  
  def name
    "#{first_name} #{last_name}"
  end
  
  def to_s
    name
  end
  
  def initials
    "#{first_name.chars.first}#{last_name.chars.first}".upcase
  end
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :player
  belongs_to :match
  belongs_to :hole
  
  validates :player, :match, :hole, :score, :presence => true
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :match
  belongs_to :captain, :class_name => 'Player'
  belongs_to :player, :class_name => 'Player'

  validates :captain, :player, :shots_captain, :shots_player, :presence => true

  def players
    [captain, player]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clubs_controller.rb
class ClubsController < InheritedResources::Base
  before_filter :authenticate_player!
  
  def create
    create! { clubs_path }
  end
  
  def update
    update! { clubs_path }
  end
  
  def destroy
    destroy! { clubs_path }
  end
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  before_filter :authenticate_player!

  def new
    new! do
      (1..18).each do |nr|
        @course.holes.build(:nr => nr)
      end
    end
  end
  
  def create
    create! { courses_path }
  end

  def update
    update! { courses_path }
  end

  def destroy
    destroy! { courses_path }
  end
end

app/controllers/matches_controller.rb
class MatchesController < InheritedResources::Base
  layout 'mobile'

  before_filter :authenticate_player!
  before_filter :only => [:show, :results, :score, :goto_hole, :prev_hole, :next_hole] do
    @match = Match.find(params[:id])
    unless @match.players.include?(current_player)
      render :text => 'Foo'
    end
  end


  def show
    if @match.finished?
      redirect_to results_match_path
    else
      show! do
        @players = @match.teams.map { |team| [team.captain, team.player] }.flatten
      end
    end
  end

  def new
    new! do
      @match.teams.build
      @match.teams.build

      @courses = Course.all.map { |course| ["#{course.name} (#{course.club.name})", course.id] }
    end
  end

  def prev_hole
    @match.prev_hole!

    redirect_to :back
  end

  def next_hole
    @match.next_hole!

    redirect_to :back
  end

  def goto_hole
    @match.goto_hole!(params[:nr].to_i)

    redirect_to :back
  end

  def results
  end

  def score
    @match.update_attributes(params[:match])
    @match.next_hole!

    if @match.finished?
      redirect_to results_match_path
    else
      redirect_to :back
    end
  end
end

app/controllers/startpage_controller.rb
class StartpageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def team_initials(team)
    [team.captain.initials, team.player.initials].join(' & ')
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/startpage_helper.rb
module StartpageHelper
end

app/views/clubs/_form.html.erb
<%= simple_form_for @club, :html => { :class => 'form-stacked' } do |form| %>
  <fieldset>
    <legend>Club information</legend>

    <%= form.input :name %>
  </fieldset>
   
  <div class="actions">
    <%= form.submit :class => 'btn' %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h2>Edit club</h2>

<%= render 'form' %>

app/views/clubs/index.html.erb
<h2>Clubs</h2>

<table class="zebra-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td>
          <%= club.name %>
        </td>
        <td>
          <%= link_to 'Edit', edit_club_path(club), :class => 'btn info' %>
          <%= link_to 'Remove', club_path(club), :method => :delete, :confirm => 'Are you sure?', :class => 'btn danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add new club', new_club_path, :class => 'btn' %>

app/views/clubs/new.html.erb
<h2>Add new club</h2>

<%= render 'form' %>

app/views/courses/_form.html.erb
<%= simple_form_for @course, :html => { :class => 'form-stacked' } do |form| %>
  <fieldset>
    <legend>Course information</legend>
   
    <%= form.association :club %>
    <%= form.input :name %>
  </fieldset>
   
  <fieldset>
    <legend>Hole information</legend>
    <table class="zebra-striped">
      <thead>
        <tr>
          <th>Hole</th>
          <th>HCP</th>
          <th>Par</th>
        </tr>
      </thead>
      <tbody>
        <% @course.holes.each do |hole| %>
          <%= form.simple_fields_for :holes, hole do |hole_form| %>
            <%= hole_form.input :nr, :as => :hidden %>
            <tr>
              <td><%= hole.nr %></td>
              <td><%= hole_form.input :hcp, :input_html => { :class => 'span2' } %></td>
              <td><%= hole_form.input :par, :input_html => { :class => 'span2' } %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </fieldset>
   
  <div class="actions">
    <%= form.submit :class => 'btn' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h2>Edit course</h2>

<%= render 'form' %>

app/views/courses/index.html.erb
<h2>Courses</h2>

<table class="zebra-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Club</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td>
          <%= course.name %>
        </td>
        <td>
          <%= course.club.name %>
        </td>
        <td>
          <%= link_to 'Edit', edit_course_path(course), :class => 'btn info' %>
          <%= link_to 'Remove', course_path(course), :method => :delete, :confirm => 'Are you sure?', :class => 'btn danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add new course', new_course_path, :class => 'btn' %>

app/views/courses/new.html.erb
<h2>Add new course</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Bästboll/Sämstboll</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="span10">
          <h1><%= link_to 'Bästboll/Sämstboll', root_path %></h1>
        </div>
        <div class="span6">
          <div class="well">
            <% if player_signed_in? %>
              <%= link_to 'Sign out', destroy_player_session_path, :method => :delete, :class => 'btn' %>
            <% else %>
              <%= link_to 'Sign up', new_player_registration_path, :class => 'btn' %>
              <%= link_to 'Sign in', new_player_session_path, :class => 'btn' %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="span16">
          <% if flash.present? %>
            <div id="flash">
              <% flash.each do |type, message| %>
                <p class="alert-message <%= type %>"><%= message %></p>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="span16">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
    <title>Bästboll/Sämstboll</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container" style="width: 480px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/matches/_team_form.html.erb
<% team.players.each do |player| %>
  <%= form.fields_for :scores, @match.score_for(player) do |score_form| %>
    <%= score_form.hidden_field :match_id, :as => :hidden %>
    <%= score_form.hidden_field :player_id, :as => :hidden, :input_html => { :value => player.id } %>
    <%= score_form.hidden_field :hole_id, :as => :hidden, :input_html => { :value => @match.hole.id } %>
    <h4><%= player.initials %></h4>
    <%= score_form.text_field :score, :as => :integer %>
  <% end %>
<% end %>

app/views/matches/index.html.erb
<h2>Matches</h2>

<table class="zebra-striped">
  <thead>
    <tr>
      <th>Match</th>
      <th>Captain team 1</th>
      <th>Player team 1</th>
      <th>Captain team 2</th>
      <th>Player team 2</th>
      <th>At hole</th>
      <th>Score</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @matches.each_with_index do |match, index| %>

      <% team_1 = match.team_1 %>
      <% team_2 = match.team_2 %>
      
      <tr>
        <td><%= index + 1 %></td>
        <td><%= team_1.captain %></td>
        <td><%= team_1.player %></td>
        <td><%= team_2.captain %></td>
        <td><%= team_2.player %></td>
        <td>
          <% if match.finished? %>
            Match finished
          <% else %>
            <%= match.hole.nr %>
          <% end %>
        </td>
        <td>
          <% score_team_1, score_team_2 = match.score %>
          
          <% if score_team_1 == score_team_2 %>
            Match tied
          <% elsif score_team_1 > score_team_2 %>
            <%= team_initials(team_1) %> lead by <b><%= score_team_1 %></b>
          <% elsif score_team_1 < score_team_2 %>
            <%= team_initials(team_2) %> lead by <b><%= score_team_2 %></b>
          <% end %>
        </td>
        <td>
          <% if match.players.include?(current_player) %>
            <% if match.finished? %>
              <%= link_to 'See results', match_path(match), :class => 'btn info' %>
            <% else %>
              <%= link_to 'Go to match', match_path(match), :class => 'btn success' %>
            <% end %>
          <% end %>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>

<%= link_to 'Start a new match', new_match_path, :class => 'btn' %>

app/views/matches/new.html.erb
<h2>Start new match</h2>

<%= simple_form_for @match do |form| %>
  <%= form.input :player_id, :as => :hidden, :input_html => { :value => current_player.id } %>
  
  <%= form.association :course, :collection => @courses %>
  <%= form.input :points_for_birdie, :as => :integer, :input_html => { :class => 'span1' } %>
  
  <% @match.teams.each_with_index do |team, index| %>
    <%= form.simple_fields_for :teams, team do |team_form| %>

      <fieldset>
        <legend>Team <%= index + 1 %></legend>
        <%= team_form.association :captain %>
        <%= team_form.input :shots_captain, :as => :integer, :input_html => { :class => 'span1' } %>
        <%= team_form.association :player %>
        <%= team_form.input :shots_player, :as => :integer, :input_html => { :class => 'span1' } %>
      </fieldset>

    <% end %>
  <% end %>

  <div class="actions">
    <%= form.submit :class => 'btn' %>
  </div>
<% end %>

app/views/matches/results.html.erb
<% if @match.finished? %>
  <h1>Match done!</h1>

  <% team_1 = @match.team_1 %>
  <% team_2 = @match.team_2 %>

  <% score_team_1, score_team_2 = @match.score %>

  <% if score_team_1 == score_team_2 %>
    <p>Match tied</p>
  <% elsif score_team_1 > score_team_2 %>
    <p>Team 1 winners:</p>
    <ul>
      <li><%= team_1.captain.name %></li>
      <li><%= team_1.player.name %></li>
    </ul>
    
    <%= score_team_1 %> UP
  <% elsif score_team_1 < score_team_2 %>
    <p>Team 2 winners:</p>
    <ul>
      <li><%= team_2.captain.name %></li>
      <li><%= team_2.player.name %></li>
    </ul>
    
    <%= score_team_2 %> UP
  <% end %>
<% else %>
  Match is not finished, see <%= link_to 'list of matches', matches_path %>.
<% end %>

app/views/matches/show.html.erb
<% score_team_1, score_team_2 = @match.score %>

<div class="row well">
  <div class="span3">
    <h1>Hole <%= @match.hole.nr %></h1>
    <span class="label">
      PAR <%= @match.hole.par %>
    </span>
    <br />
    <span class="label notice">
      HCP <%= @match.hole.hcp %>
    </span>
  </div>
  <div class="span2">
    <h3><%= team_initials(@match.team_1) %></h3>
    <% if score_team_1 == score_team_2 %>
      AS
    <% elsif score_team_1 > score_team_2 %>
      <%= score_team_1 %> UP
    <% elsif score_team_1 < score_team_2 %>
      -<%= score_team_2 %> DOWN
    <% end %>
  </div>
  <div class="span2">
    <h3><%= team_initials(@match.team_2) %></h3>
    <% if score_team_2 == score_team_1 %>
      AS
    <% elsif score_team_2 > score_team_1 %>
      <%= score_team_2 %> UP
    <% elsif score_team_2 < score_team_1 %>
      -<%= score_team_1 %> DOWN
    <% end %>
  </div>
</div>

<%= form_for(@match, :url => score_match_path(@match), :method => :post) do |form| %>
  <div class="row well">
    <div style="width: 220px; float: left; margin-left: 10px;">
      <h2 style="text-align: center;">Team 1</h2>
      
      <%= render 'team_form', :team => @match.team_1, :form => form %>
    </div>
    <div style="width: 220px; float: left; margin-left: 10px;">
      <h2 style="text-align: center;">Team 2</h2>

      <%= render 'team_form', :team => @match.team_2, :form => form %>
    </div>
    <div class="clearfix"></div>
  </div>

  <div class="actions" style="float: center;">
    <% unless @match.hole.nr == 1 %>
      <%= link_to 'Prev hole', prev_hole_match_path(@match), :class => 'btn', :method => :put %>
    <% end %>
    <% if @match.hole.nr == 18 %>
      <%= form.submit :class => 'btn', :value => 'End match' %>
    <% else %>
      <%= form.submit :class => 'btn', :value => 'Next hole' %>
    <% end %>
  </div>
<% end %>

app/views/startpage/index.html.erb
<% if player_signed_in? %>
  <h2>Clubs</h2>
  <div class="well">
    <%= link_to 'Add new club', new_club_path, :class => 'btn' %>
    <%= link_to 'List of clubs', clubs_path, :class => 'btn' %>
  </div>

  <h2>Courses</h2>
  <div class="well">
    <%= link_to 'Add new course', new_course_path, :class => 'btn' %>
    <%= link_to 'List of courses', courses_path, :class => 'btn' %>
  </div>

  <h2>Play</h2>
  <div class="well">
    <%= link_to 'Start a new match', new_match_path, :class => 'btn' %>
    <%= link_to 'List matches', matches_path, :class => 'btn' %>
  </div>
<% end %>